"""empty message

Revision ID: 759ef18779c8
Revises: b5991901f37f
Create Date: 2021-12-20 09:57:02.087211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759ef18779c8'
down_revision = 'b5991901f37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
