"""empty message

Revision ID: d21bdda7e47e
Revises: 37bd61514e88
Create Date: 2021-12-26 21:50:28.556826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21bdda7e47e'
down_revision = '37bd61514e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('background_image_name', sa.String(), default='', nullable=True))
    op.add_column('user', sa.Column('profile_image_name', sa.String(), default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image_name')
    op.drop_column('user', 'background_image_name')
    # ### end Alembic commands ###
