SECRET_KEY = 'SUPERMEGASECRET'
SECURITY_PASSWORD_SALT = 'SUPERMEGASECRET2'

SQLALCHEMY_DATABASE_URI = 'sqlite:///app.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False

CKEDITOR_SERVE_LOCAL = True
CKEDITOR_ENABLE_CODESNIPPET = True
